### ISSUE TITLE
Failed to build 'beerapi'

### ISSUE THREAD

**Issue by nsejim** [gravitee-io/devfestlille-2018#1]
When running "docker-compose build", I got the following error:

Service 'beerapi' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder539971474/target/beer-app-1.0-SNAPSHOT-fat.jar: no such file or directory

**Comment by tarminator** [comment]
@nsejim there are a few steps missing from the readme and some pre-reqs required to get this up and running.   I'm using a minimal CentOS 7 Install.

**Pre-requisites:**

- Download and install Oracle JDK - this one worked jdk-8u191-linux-x64.  
- yum install maven. 

**Installation steps**

- `git clone https://github.com/gravitee-io/devfestlille-2018.git`
- cd into the beer-app directory and run `maven clean install`.  

You should see something similar to below:
```
[INFO] Installing /home/test/gravitee/devfestlille-2018/beer-app/target/beer-app-1.0-SNAPSHOT.jar to /home/test/.m2/repository/io/vertx/blog/beer-app/1.0-SNAPSHOT/beer-app-1.0-SNAPSHOT.jar
[INFO] Installing /home/test/gravitee/devfestlille-2018/beer-app/pom.xml to /home/test/.m2/repository/io/vertx/blog/beer-app/1.0-SNAPSHOT/beer-app-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.775s
[INFO] Finished at: Tue Oct 23 11:55:52 IST 2018
[INFO] Final Memory: 21M/57M
[INFO] ------------------------------------------------------------------------
```
`cd ..`

```
docker-compose pull
docker-compose build
docker-compose up
```

**Comment by nsejim** [comment]
It works now
